### ISSUE TITLE
No Data.PrettyPrint module?

### ISSUE THREAD

**Issue by soupi** [cdparks/lambda-machine#1]
Hi,

I'm trying to build `lambda-machine` and I get an error that, for example, `Data.Syntax` is trying to import the module `Data.PrettyPrint` but there's no such module in the repo.

**Comment by cdparks** [comment]
Whoops, when I broke `Data.PrettyPrint` out into its own module, I failed to add it to the repo. Of course it kept building on my machine. It's fixed in latest. Thanks for the heads up!
