### ISSUE TITLE
Explicit α-conversion

### ISSUE THREAD

**Issue by ayberkt** [cdparks/lambda-machine#3]
α-captures are correctly handled in terms of semantics, but the displayed expression doesn't display the α-conversion.
```
4) z y z
3) (λx. x y) z z
2) (λy. (λx. x y) y z) z
1) (λx. λy. x y z) (λx. x y) z
```
At step 2 we should have something like (λn. (λx. x y) n z) z so that the conversion is made explicit.

A minor problem, but wanted to make note of it in case there are people confused. It should be trivial to fix.

**Comment by cdparks** [comment]
Thanks for the heads-up!
