### ISSUE TITLE
Support PureScript 0.11?

### ISSUE THREAD

**Issue by FranklinChen** [cdparks/lambda-machine#5]
Consider supporting PureScript 0.11?

**Comment by cdparks** [comment]
Hey @FranklinChen, I'm on vacation now, but I'll look into this when I get back (end of May).

**Comment by FranklinChen** [comment]
Thanks, no rush at all.

**Comment by cdparks** [comment]
Updated to 0.11.4 just now. Thanks!

**Comment by FranklinChen** [comment]
Is there supposed to be a `package.json`?

```
$ make
make: *** No rule to make target `package.json', needed by `deps'.  Stop.
```

**Comment by cdparks** [comment]
Gah, yup. Added just now.
